apiVersion: v1
kind: Secret
metadata:
  name: livekit-config
  namespace: livekit
type: Opaque
stringData:
  config.yaml: |
    port: 7880
    rtc:
      udp_port: 7881
      tcp_port: 7882
    keys:
      devkey: devsecret

