apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  namespace: livekit
type: Opaque
stringData:
  openai_key: YOUR_OPENAI_KEY
  assemblyai_key: YOUR_ASSEMBLYAI_KEY
  cartesia_key: YOUR_CARTESIA_KEY

