swagger: "2.0"
info:
  title: training-api
  version: 1.0.0
paths:
  /:
    get:
      x-google-backend:
        address: https://YOUR_CLOUD_RUN_URL
      responses:
        "200":
          description: OK

